[workspace]
resolver = "2"
members = [
    "crates/neutron-protocol",
    "crates/neutron-protocol/fuzz",
    "crates/neutron-world",
    "crates/neutron-worldgen",
    "crates/neutron-server",
    "crates/neutron-bench-server",
    "crates/neutron-sim",
    "tools/ref-extract",
    "tools/neutron-hash",
    "tools/chunk-dump",
]
