#!/usr/bin/env python3
"""Extract minecraft structure .nbt templates into Rust const tables.

Usage: python3 tools/nbt-extract/mc_struct_nbt.py <jar> <out.rs> [struct_dir]
Parses data/minecraft/structure/<struct_dir>/*.nbt (gzip NBT);
default struct_dir=ruined_portal.
Emits (size_x,size_y,size_z, cells=[(x,y,z,pal_idx)], entities_ignored,
data_markers=[]) tables plus a global palette of 'Name|k=v;k=v' strings.
"""
import gzip, io, json, struct, sys, zipfile

class R:
    def __init__(self, b):
        self.b = b
        self.i = 0
    def take(self, n):
        v = self.b[self.i:self.i+n]
        self.i += n
        return v
    def u1(self):
        return self.take(1)[0]
    def u2(self):
        return struct.unpack('>H', self.take(2))[0]
    def u4(self):
        return struct.unpack('>i', self.take(4))[0]
    def u8(self):
        return struct.unpack('>q', self.take(8))[0]
    def f4(self):
        return struct.unpack('>f', self.take(4))[0]
    def f8(self):
        return struct.unpack('>d', self.take(8))[0]
    def s(self):
        n = self.u2()
        return self.take(n).decode('utf-8', 'replace')

def payload(r, t):
    if t == 0:
        return None
    if t == 1:
        return r.u1()
    if t == 2:
        return r.u2()
    if t == 3:
        return r.u4()
    if t == 4:
        return r.u8()
    if t == 5:
        return r.f4()
    if t == 6:
        return r.f8()
    if t == 7:
        n = r.u4()
        return list(r.take(n))
    if t == 8:
        return r.s()
    if t == 9:
        et = r.u1()
        n = r.u4()
        return [payload(r, et) for _ in range(n)]
    if t == 10:
        d = {}
        while True:
            tt = r.u1()
            if tt == 0:
                break
            name = r.s()
            d[name] = payload(r, tt)
        return d
    if t == 11:
        n = r.u4()
        return [r.u4() for _ in range(n)]
    if t == 12:
        n = r.u4()
        return [r.u8() for _ in range(n)]
    raise ValueError(t)

def parse(b):
    r = R(b)
    t = r.u1()
    assert t == 10
    name = r.s()
    return payload(r, 10)

def fmt_props(p):
    if not p:
        return ''
    items = []
    for k in sorted(p.keys()):
        items.append(f'{k}={p[k]}')
    return '|' + ';'.join(items)

def main(jar_path, out_path, struct_dir='ruined_portal'):
    z = zipfile.ZipFile(jar_path)
    prefix = f'data/minecraft/structure/{struct_dir}/'
    names = sorted(n for n in z.namelist() if n.startswith(prefix) and n.endswith('.nbt'))
    # const names prefixed by subdirectory to avoid collisions (ancient_city has city/...)
    def const_name(n):
        rel = n[len(prefix):-4]
        return rel.upper().replace('/', '_').replace('.', '_')
    palettes = {}
    out = []
    consts = []
    for n in names:
        base = const_name(n)
        data = parse(gzip.decompress(z.read(n)))
        size = data['size']
        pal_raw = data['palette']
        pal_ids = []
        for e in pal_raw:
            key = e['Name'] + fmt_props(e.get('Properties'))
            if key not in palettes:
                palettes[key] = len(palettes)
            pal_ids.append(palettes[key])
        cells = []
        markers = []
        for bi, blk in enumerate(data['blocks']):
            x, y, zz = blk['pos']
            st = blk['state']
            if 'nbt' in blk:
                nbtt = blk['nbt']
                mid = nbtt.get('id', '')
                fs = nbtt.get('final_state', '')
                # jigsaw extras read by JigsawPlacement: name, pool,
                # placement_priority, joint.
                if mid == 'minecraft:jigsaw':
                    markers.append((bi, x, y, zz, pal_ids[st], str(mid), str(fs),
                                    str(nbtt.get('name', '')), str(nbtt.get('pool', '')),
                                    int(nbtt.get('placement_priority', 0)),
                                    str(nbtt.get('joint', 'alignable')),
                                    str(nbtt.get('target', ''))))
                else:
                    markers.append((bi, x, y, zz, pal_ids[st], str(mid), str(fs),
                                    '', '', 0, '', ''))
            else:
                cells.append((bi, x, y, zz, pal_ids[st]))
        out.append((base, size, pal_raw, cells, markers))

    with open(out_path, 'w') as f:
        f.write('// Ruined portal structure templates extracted from the 26.2 server\n')
        f.write('// jar (`data/minecraft/structure/ruined_portal/*.nbt`). Generated by\n')
        f.write('// tools/nbt-extract/mc_struct_nbt.py -- do not hand-edit.\n\n')
        f.write('/// palette entries: vanilla block id + properties (`name|k=v;k=v`).\n')
        f.write('#[rustfmt::skip]\n')
        f.write('pub(crate) static PALETTE: &[&str] = &[\n')
        for k in sorted(palettes, key=palettes.get):
            f.write(f'    "{k}",\n')
        f.write('];\n\n')
        f.write('pub(crate) struct Tpl {\n')
        f.write('    pub(crate) size: [i32; 3],\n')
        f.write('    /// (nbt_index, x, y, z, pal) — nbt_index = position in the\n')
        f.write('    /// template `blocks` array (vanilla `StructureTemplate` visit order).\n')
        f.write('    pub(crate) cells: &\'static [(u16, i32, i32, i32, u16)],\n')
        f.write('    /// block-entity cells: (nbt_index,x,y,z,pal,id,final_state,\n')
        f.write('    /// jigsaw_name,jigsaw_pool,jigsaw_priority,jigsaw_joint).\n')
        f.write('    pub(crate) marked: &\'static [(u16, i32, i32, i32, u16, &\'static str, &\'static str,\n')
        f.write('        &\'static str, &\'static str, i32, &\'static str, &\'static str)],\n')
        f.write('}\n\n')
        for base, size, _, cells, markers in out:
            f.write(f'/// {base.lower()} (template coords, NBT block order)\n')
            f.write(f'#[rustfmt::skip]\npub(crate) static {base}: Tpl = Tpl {{ size: [{size[0]}, {size[1]}, {size[2]}], cells: &[\n')
            f.write(',\n'.join(f'({i},{x},{y},{z},{p})' for i, x, y, z, p in cells))
            f.write('\n], marked: &[')
            f.write(', '.join(f'({i},{x},{y},{z},{p},"{m}","{fs}","{jn}","{jp}",{pr},"{jt}","{tg}")' for i, x, y, z, p, m, fs, jn, jp, pr, jt, tg in markers))
            f.write('] };\n\n')
            consts.append(base)


    # template-name lookup (assembly + placement resolve by pool string).
    with open(out_path, 'a') as f:
        f.write('\n/// Resolve a template const by its pool-JSON location suffix\n')
        f.write('/// (e.g. `CITY_CENTER_CITY_CENTER_1`). Missing-on-disk templates\n')
        f.write('/// (vanilla data references one) resolve to `None`.\n')
        f.write("pub(crate) fn tpl_by_name(name: &str) -> Option<&'static Tpl> {\n")
        f.write('    match name {\n')
        for c in consts:
            f.write(f'        "{c}" => Some(&{c}),\n')
        f.write('        _ => None,\n')
        f.write('    }\n')
        f.write('}\n')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else 'ruined_portal')

