//! Embedded vanilla 26.2 datapack worldgen JSONs (`include_str!`).
//!
//! Source: `tools/vanilla-extract/server-classes/data/minecraft/worldgen/`.
//! Prefer editing the JSON under `src/data/` and re-extracting; do not add
//! new `include_str!` arms by hand unless the extract script is updated too.

/// Return the embedded JSON content for a datapack path (relative to worldgen/).
pub fn datapack_json(path: &str) -> Option<&'static str> {
    match path {
        "density_function/end/base_3d_noise.json" => Some(include_str!("data/worldgen/density_function/end/base_3d_noise.json")),
        "density_function/end/sloped_cheese.json" => Some(include_str!("data/worldgen/density_function/end/sloped_cheese.json")),
        "density_function/nether/base_3d_noise.json" => Some(include_str!("data/worldgen/density_function/nether/base_3d_noise.json")),
        "density_function/overworld/base_3d_noise.json" => Some(include_str!("data/worldgen/density_function/overworld/base_3d_noise.json")),
        "density_function/overworld/caves/entrances.json" => Some(include_str!("data/worldgen/density_function/overworld/caves/entrances.json")),
        "density_function/overworld/caves/noodle.json" => Some(include_str!("data/worldgen/density_function/overworld/caves/noodle.json")),
        "density_function/overworld/caves/pillars.json" => Some(include_str!("data/worldgen/density_function/overworld/caves/pillars.json")),
        "density_function/overworld/caves/spaghetti_2d.json" => Some(include_str!("data/worldgen/density_function/overworld/caves/spaghetti_2d.json")),
        "density_function/overworld/caves/spaghetti_2d_thickness_modulator.json" => Some(include_str!("data/worldgen/density_function/overworld/caves/spaghetti_2d_thickness_modulator.json")),
        "density_function/overworld/caves/spaghetti_roughness_function.json" => Some(include_str!("data/worldgen/density_function/overworld/caves/spaghetti_roughness_function.json")),
        "density_function/overworld/continents.json" => Some(include_str!("data/worldgen/density_function/overworld/continents.json")),
        "density_function/overworld/depth.json" => Some(include_str!("data/worldgen/density_function/overworld/depth.json")),
        "density_function/overworld/erosion.json" => Some(include_str!("data/worldgen/density_function/overworld/erosion.json")),
        "density_function/overworld/factor.json" => Some(include_str!("data/worldgen/density_function/overworld/factor.json")),
        "density_function/overworld/jaggedness.json" => Some(include_str!("data/worldgen/density_function/overworld/jaggedness.json")),
        "density_function/overworld/offset.json" => Some(include_str!("data/worldgen/density_function/overworld/offset.json")),
        "density_function/overworld/ridges.json" => Some(include_str!("data/worldgen/density_function/overworld/ridges.json")),
        "density_function/overworld/ridges_folded.json" => Some(include_str!("data/worldgen/density_function/overworld/ridges_folded.json")),
        "density_function/overworld/sloped_cheese.json" => Some(include_str!("data/worldgen/density_function/overworld/sloped_cheese.json")),
        "density_function/overworld_amplified/depth.json" => Some(include_str!("data/worldgen/density_function/overworld_amplified/depth.json")),
        "density_function/overworld_amplified/factor.json" => Some(include_str!("data/worldgen/density_function/overworld_amplified/factor.json")),
        "density_function/overworld_amplified/jaggedness.json" => Some(include_str!("data/worldgen/density_function/overworld_amplified/jaggedness.json")),
        "density_function/overworld_amplified/offset.json" => Some(include_str!("data/worldgen/density_function/overworld_amplified/offset.json")),
        "density_function/overworld_amplified/sloped_cheese.json" => Some(include_str!("data/worldgen/density_function/overworld_amplified/sloped_cheese.json")),
        "density_function/overworld_large_biomes/continents.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/continents.json")),
        "density_function/overworld_large_biomes/depth.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/depth.json")),
        "density_function/overworld_large_biomes/erosion.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/erosion.json")),
        "density_function/overworld_large_biomes/factor.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/factor.json")),
        "density_function/overworld_large_biomes/jaggedness.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/jaggedness.json")),
        "density_function/overworld_large_biomes/offset.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/offset.json")),
        "density_function/overworld_large_biomes/sloped_cheese.json" => Some(include_str!("data/worldgen/density_function/overworld_large_biomes/sloped_cheese.json")),
        "density_function/shift_x.json" => Some(include_str!("data/worldgen/density_function/shift_x.json")),
        "density_function/shift_z.json" => Some(include_str!("data/worldgen/density_function/shift_z.json")),
        "density_function/y.json" => Some(include_str!("data/worldgen/density_function/y.json")),
        "density_function/zero.json" => Some(include_str!("data/worldgen/density_function/zero.json")),
        "multi_noise_biome_source_parameter_list/nether.json" => Some(include_str!("data/worldgen/multi_noise_biome_source_parameter_list/nether.json")),
        "multi_noise_biome_source_parameter_list/overworld.json" => Some(include_str!("data/worldgen/multi_noise_biome_source_parameter_list/overworld.json")),
        "noise/aquifer_barrier.json" => Some(include_str!("data/worldgen/noise/aquifer_barrier.json")),
        "noise/aquifer_fluid_level_floodedness.json" => Some(include_str!("data/worldgen/noise/aquifer_fluid_level_floodedness.json")),
        "noise/aquifer_fluid_level_spread.json" => Some(include_str!("data/worldgen/noise/aquifer_fluid_level_spread.json")),
        "noise/aquifer_lava.json" => Some(include_str!("data/worldgen/noise/aquifer_lava.json")),
        "noise/badlands_pillar.json" => Some(include_str!("data/worldgen/noise/badlands_pillar.json")),
        "noise/badlands_pillar_roof.json" => Some(include_str!("data/worldgen/noise/badlands_pillar_roof.json")),
        "noise/badlands_surface.json" => Some(include_str!("data/worldgen/noise/badlands_surface.json")),
        "noise/calcite.json" => Some(include_str!("data/worldgen/noise/calcite.json")),
        "noise/cave_cheese.json" => Some(include_str!("data/worldgen/noise/cave_cheese.json")),
        "noise/cave_entrance.json" => Some(include_str!("data/worldgen/noise/cave_entrance.json")),
        "noise/cave_layer.json" => Some(include_str!("data/worldgen/noise/cave_layer.json")),
        "noise/clay_bands_offset.json" => Some(include_str!("data/worldgen/noise/clay_bands_offset.json")),
        "noise/continentalness.json" => Some(include_str!("data/worldgen/noise/continentalness.json")),
        "noise/continentalness_large.json" => Some(include_str!("data/worldgen/noise/continentalness_large.json")),
        "noise/erosion.json" => Some(include_str!("data/worldgen/noise/erosion.json")),
        "noise/erosion_large.json" => Some(include_str!("data/worldgen/noise/erosion_large.json")),
        "noise/gravel.json" => Some(include_str!("data/worldgen/noise/gravel.json")),
        "noise/gravel_layer.json" => Some(include_str!("data/worldgen/noise/gravel_layer.json")),
        "noise/ice.json" => Some(include_str!("data/worldgen/noise/ice.json")),
        "noise/iceberg_pillar.json" => Some(include_str!("data/worldgen/noise/iceberg_pillar.json")),
        "noise/iceberg_pillar_roof.json" => Some(include_str!("data/worldgen/noise/iceberg_pillar_roof.json")),
        "noise/iceberg_surface.json" => Some(include_str!("data/worldgen/noise/iceberg_surface.json")),
        "noise/jagged.json" => Some(include_str!("data/worldgen/noise/jagged.json")),
        "noise/nether/temperature.json" => Some(include_str!("data/worldgen/noise/nether/temperature.json")),
        "noise/nether/vegetation.json" => Some(include_str!("data/worldgen/noise/nether/vegetation.json")),
        "noise/nether_state_selector.json" => Some(include_str!("data/worldgen/noise/nether_state_selector.json")),
        "noise/nether_wart.json" => Some(include_str!("data/worldgen/noise/nether_wart.json")),
        "noise/netherrack.json" => Some(include_str!("data/worldgen/noise/netherrack.json")),
        "noise/noodle.json" => Some(include_str!("data/worldgen/noise/noodle.json")),
        "noise/noodle_ridge_a.json" => Some(include_str!("data/worldgen/noise/noodle_ridge_a.json")),
        "noise/noodle_ridge_b.json" => Some(include_str!("data/worldgen/noise/noodle_ridge_b.json")),
        "noise/noodle_thickness.json" => Some(include_str!("data/worldgen/noise/noodle_thickness.json")),
        "noise/offset.json" => Some(include_str!("data/worldgen/noise/offset.json")),
        "noise/ore_gap.json" => Some(include_str!("data/worldgen/noise/ore_gap.json")),
        "noise/ore_vein_a.json" => Some(include_str!("data/worldgen/noise/ore_vein_a.json")),
        "noise/ore_vein_b.json" => Some(include_str!("data/worldgen/noise/ore_vein_b.json")),
        "noise/ore_veininess.json" => Some(include_str!("data/worldgen/noise/ore_veininess.json")),
        "noise/packed_ice.json" => Some(include_str!("data/worldgen/noise/packed_ice.json")),
        "noise/patch.json" => Some(include_str!("data/worldgen/noise/patch.json")),
        "noise/pillar.json" => Some(include_str!("data/worldgen/noise/pillar.json")),
        "noise/pillar_rareness.json" => Some(include_str!("data/worldgen/noise/pillar_rareness.json")),
        "noise/pillar_thickness.json" => Some(include_str!("data/worldgen/noise/pillar_thickness.json")),
        "noise/powder_snow.json" => Some(include_str!("data/worldgen/noise/powder_snow.json")),
        "noise/ridge.json" => Some(include_str!("data/worldgen/noise/ridge.json")),
        "noise/soul_sand_layer.json" => Some(include_str!("data/worldgen/noise/soul_sand_layer.json")),
        "noise/spaghetti_2d.json" => Some(include_str!("data/worldgen/noise/spaghetti_2d.json")),
        "noise/spaghetti_2d_elevation.json" => Some(include_str!("data/worldgen/noise/spaghetti_2d_elevation.json")),
        "noise/spaghetti_2d_modulator.json" => Some(include_str!("data/worldgen/noise/spaghetti_2d_modulator.json")),
        "noise/spaghetti_2d_thickness.json" => Some(include_str!("data/worldgen/noise/spaghetti_2d_thickness.json")),
        "noise/spaghetti_3d_1.json" => Some(include_str!("data/worldgen/noise/spaghetti_3d_1.json")),
        "noise/spaghetti_3d_2.json" => Some(include_str!("data/worldgen/noise/spaghetti_3d_2.json")),
        "noise/spaghetti_3d_rarity.json" => Some(include_str!("data/worldgen/noise/spaghetti_3d_rarity.json")),
        "noise/spaghetti_3d_thickness.json" => Some(include_str!("data/worldgen/noise/spaghetti_3d_thickness.json")),
        "noise/spaghetti_roughness.json" => Some(include_str!("data/worldgen/noise/spaghetti_roughness.json")),
        "noise/spaghetti_roughness_modulator.json" => Some(include_str!("data/worldgen/noise/spaghetti_roughness_modulator.json")),
        "noise/sulfur_cave_gradient.json" => Some(include_str!("data/worldgen/noise/sulfur_cave_gradient.json")),
        "noise/surface.json" => Some(include_str!("data/worldgen/noise/surface.json")),
        "noise/surface_secondary.json" => Some(include_str!("data/worldgen/noise/surface_secondary.json")),
        "noise/surface_swamp.json" => Some(include_str!("data/worldgen/noise/surface_swamp.json")),
        "noise/temperature.json" => Some(include_str!("data/worldgen/noise/temperature.json")),
        "noise/temperature_large.json" => Some(include_str!("data/worldgen/noise/temperature_large.json")),
        "noise/vegetation.json" => Some(include_str!("data/worldgen/noise/vegetation.json")),
        "noise/vegetation_large.json" => Some(include_str!("data/worldgen/noise/vegetation_large.json")),
        "noise_settings_overworld.json" => Some(include_str!("data/worldgen/noise_settings_overworld.json")),
        _ => None,
    }
}

/// All embedded JSON paths (relative to worldgen/).
pub fn all_paths() -> &'static [&'static str] {
    &[
        "density_function/end/base_3d_noise.json",
        "density_function/end/sloped_cheese.json",
        "density_function/nether/base_3d_noise.json",
        "density_function/overworld/base_3d_noise.json",
        "density_function/overworld/caves/entrances.json",
        "density_function/overworld/caves/noodle.json",
        "density_function/overworld/caves/pillars.json",
        "density_function/overworld/caves/spaghetti_2d.json",
        "density_function/overworld/caves/spaghetti_2d_thickness_modulator.json",
        "density_function/overworld/caves/spaghetti_roughness_function.json",
        "density_function/overworld/continents.json",
        "density_function/overworld/depth.json",
        "density_function/overworld/erosion.json",
        "density_function/overworld/factor.json",
        "density_function/overworld/jaggedness.json",
        "density_function/overworld/offset.json",
        "density_function/overworld/ridges.json",
        "density_function/overworld/ridges_folded.json",
        "density_function/overworld/sloped_cheese.json",
        "density_function/overworld_amplified/depth.json",
        "density_function/overworld_amplified/factor.json",
        "density_function/overworld_amplified/jaggedness.json",
        "density_function/overworld_amplified/offset.json",
        "density_function/overworld_amplified/sloped_cheese.json",
        "density_function/overworld_large_biomes/continents.json",
        "density_function/overworld_large_biomes/depth.json",
        "density_function/overworld_large_biomes/erosion.json",
        "density_function/overworld_large_biomes/factor.json",
        "density_function/overworld_large_biomes/jaggedness.json",
        "density_function/overworld_large_biomes/offset.json",
        "density_function/overworld_large_biomes/sloped_cheese.json",
        "density_function/shift_x.json",
        "density_function/shift_z.json",
        "density_function/y.json",
        "density_function/zero.json",
        "multi_noise_biome_source_parameter_list/nether.json",
        "multi_noise_biome_source_parameter_list/overworld.json",
        "noise/aquifer_barrier.json",
        "noise/aquifer_fluid_level_floodedness.json",
        "noise/aquifer_fluid_level_spread.json",
        "noise/aquifer_lava.json",
        "noise/badlands_pillar.json",
        "noise/badlands_pillar_roof.json",
        "noise/badlands_surface.json",
        "noise/calcite.json",
        "noise/cave_cheese.json",
        "noise/cave_entrance.json",
        "noise/cave_layer.json",
        "noise/clay_bands_offset.json",
        "noise/continentalness.json",
        "noise/continentalness_large.json",
        "noise/erosion.json",
        "noise/erosion_large.json",
        "noise/gravel.json",
        "noise/gravel_layer.json",
        "noise/ice.json",
        "noise/iceberg_pillar.json",
        "noise/iceberg_pillar_roof.json",
        "noise/iceberg_surface.json",
        "noise/jagged.json",
        "noise/nether/temperature.json",
        "noise/nether/vegetation.json",
        "noise/nether_state_selector.json",
        "noise/nether_wart.json",
        "noise/netherrack.json",
        "noise/noodle.json",
        "noise/noodle_ridge_a.json",
        "noise/noodle_ridge_b.json",
        "noise/noodle_thickness.json",
        "noise/offset.json",
        "noise/ore_gap.json",
        "noise/ore_vein_a.json",
        "noise/ore_vein_b.json",
        "noise/ore_veininess.json",
        "noise/packed_ice.json",
        "noise/patch.json",
        "noise/pillar.json",
        "noise/pillar_rareness.json",
        "noise/pillar_thickness.json",
        "noise/powder_snow.json",
        "noise/ridge.json",
        "noise/soul_sand_layer.json",
        "noise/spaghetti_2d.json",
        "noise/spaghetti_2d_elevation.json",
        "noise/spaghetti_2d_modulator.json",
        "noise/spaghetti_2d_thickness.json",
        "noise/spaghetti_3d_1.json",
        "noise/spaghetti_3d_2.json",
        "noise/spaghetti_3d_rarity.json",
        "noise/spaghetti_3d_thickness.json",
        "noise/spaghetti_roughness.json",
        "noise/spaghetti_roughness_modulator.json",
        "noise/sulfur_cave_gradient.json",
        "noise/surface.json",
        "noise/surface_secondary.json",
        "noise/surface_swamp.json",
        "noise/temperature.json",
        "noise/temperature_large.json",
        "noise/vegetation.json",
        "noise/vegetation_large.json",
        "noise_settings_overworld.json",
    ]
}
