//! Internal worldgen block IDs stored in [`GeneratedChunk::blocks`](crate::GeneratedChunk).
//!
//! Compact `u16` values, **not** protocol state IDs. The server remaps them
//! in `neutron-server::protocol_data`. The parity tool maps names for NBT.
//!
//! Copyright (c) 2026 Neutron Contributors -- MIT License

/// Minecraft block IDs used during chunk generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    Granite = 2,
    Diorite = 3,
    Andesite = 4,
    Dirt = 10,
    CoarseDirt = 11,
    GrassBlock = 12,
    Podzol = 14,
    Mycelium = 15,
    Cobblestone = 20,
    Sand = 24,
    RedSand = 25,
    Gravel = 26,
    GoldOre = 27,
    IronOre = 28,
    CoalOre = 29,
    CopperOre = 30,
    DeepslateIronOre = 31,
    RawIronBlock = 32,
    Bedrock = 33,
    RawCopperBlock = 34,
    DeepslateCoalOre = 35,
    DeepslateGoldOre = 36,
    DeepslateCopperOre = 37,
    DeepslateDiamondOre = 38,
    DeepslateRedstoneOre = 39,
    DeepslateLapisOre = 42,
    DiamondOre = 43,
    RedstoneOre = 44,
    LapisOre = 45,
    OakLog = 40,
    OakLeaves = 41,
    Water = 50,
    Lava = 51,
    Sandstone = 52,
    RedSandstone = 53,
    Ice = 54,
    Snow = 55,
    Clay = 56,
    PackedIce = 57,
    PowderSnow = 58,
    Terracotta = 59,
    WhiteTerracotta = 60,
    OrangeTerracotta = 61,
    BrownTerracotta = 62,
    BlackTerracotta = 63,
    Mud = 64,
    Deepslate = 65,
    Tuff = 66,
    Calcite = 67,
    BlueIce = 68,
    YellowTerracotta = 69,
    RedTerracotta = 70,
    LightGrayTerracotta = 71,
    /// Placeholder for 26.2 sulfur caves until palette is expanded.
    Cinnabar = 72,
    Sulfur = 73,
    Sculk = 74,
    SculkCatalyst = 75,
    SculkVein = 76,
    SculkSensor = 77,
    SculkShrieker = 78,
    MossBlock = 79,
    ShortGrass = 80,
    /// Surface leaf litter (1.21+).
    LeafLitter = 81,
    DarkOakLog = 82,
    DarkOakLeaves = 83,
    OakPlanks = 84,
    OakFence = 85,
    MossCarpet = 86,
    CaveVinesPlant = 87,
    CaveVines = 88,
    PaleOakLog = 89,
    PaleOakLeaves = 90,
    PaleMossBlock = 91,
    PaleMossCarpet = 92,
    Azalea = 93,
    FloweringAzalea = 94,
    HangingRoots = 95,
    RootedDirt = 96,
    PaleHangingMoss = 97,
    CreakingHeart = 98,
}

impl BlockId {
    pub fn as_u16(self) -> u16 {
        self as u16
    }

    pub fn from_u16(v: u16) -> Option<Self> {
        match v {
            0 => Some(Self::Air),
            1 => Some(Self::Stone),
            2 => Some(Self::Granite),
            3 => Some(Self::Diorite),
            4 => Some(Self::Andesite),
            10 => Some(Self::Dirt),
            11 => Some(Self::CoarseDirt),
            12 => Some(Self::GrassBlock),
            14 => Some(Self::Podzol),
            15 => Some(Self::Mycelium),
            20 => Some(Self::Cobblestone),
            24 => Some(Self::Sand),
            25 => Some(Self::RedSand),
            26 => Some(Self::Gravel),
            27 => Some(Self::GoldOre),
            28 => Some(Self::IronOre),
            29 => Some(Self::CoalOre),
            30 => Some(Self::CopperOre),
            31 => Some(Self::DeepslateIronOre),
            32 => Some(Self::RawIronBlock),
            33 => Some(Self::Bedrock),
            34 => Some(Self::RawCopperBlock),
            35 => Some(Self::DeepslateCoalOre),
            36 => Some(Self::DeepslateGoldOre),
            37 => Some(Self::DeepslateCopperOre),
            38 => Some(Self::DeepslateDiamondOre),
            39 => Some(Self::DeepslateRedstoneOre),
            40 => Some(Self::OakLog),
            41 => Some(Self::OakLeaves),
            42 => Some(Self::DeepslateLapisOre),
            43 => Some(Self::DiamondOre),
            44 => Some(Self::RedstoneOre),
            45 => Some(Self::LapisOre),
            50 => Some(Self::Water),
            51 => Some(Self::Lava),
            52 => Some(Self::Sandstone),
            53 => Some(Self::RedSandstone),
            54 => Some(Self::Ice),
            55 => Some(Self::Snow),
            56 => Some(Self::Clay),
            57 => Some(Self::PackedIce),
            58 => Some(Self::PowderSnow),
            59 => Some(Self::Terracotta),
            60 => Some(Self::WhiteTerracotta),
            61 => Some(Self::OrangeTerracotta),
            62 => Some(Self::BrownTerracotta),
            63 => Some(Self::BlackTerracotta),
            64 => Some(Self::Mud),
            65 => Some(Self::Deepslate),
            66 => Some(Self::Tuff),
            67 => Some(Self::Calcite),
            68 => Some(Self::BlueIce),
            69 => Some(Self::YellowTerracotta),
            70 => Some(Self::RedTerracotta),
            71 => Some(Self::LightGrayTerracotta),
            72 => Some(Self::Cinnabar),
            73 => Some(Self::Sulfur),
            74 => Some(Self::Sculk),
            75 => Some(Self::SculkCatalyst),
            76 => Some(Self::SculkVein),
            77 => Some(Self::SculkSensor),
            78 => Some(Self::SculkShrieker),
            79 => Some(Self::MossBlock),
            80 => Some(Self::ShortGrass),
            81 => Some(Self::LeafLitter),
            82 => Some(Self::DarkOakLog),
            83 => Some(Self::DarkOakLeaves),
            84 => Some(Self::OakPlanks),
            85 => Some(Self::OakFence),
            86 => Some(Self::MossCarpet),
            87 => Some(Self::CaveVinesPlant),
            88 => Some(Self::CaveVines),
            89 => Some(Self::PaleOakLog),
            90 => Some(Self::PaleOakLeaves),
            91 => Some(Self::PaleMossBlock),
            92 => Some(Self::PaleMossCarpet),
            93 => Some(Self::Azalea),
            94 => Some(Self::FloweringAzalea),
            95 => Some(Self::HangingRoots),
            96 => Some(Self::RootedDirt),
            97 => Some(Self::PaleHangingMoss),
            _ => None,
        }
    }

    pub fn is_air(self) -> bool {
        self == Self::Air
    }

    pub fn is_fluid(self) -> bool {
        matches!(self, Self::Water | Self::Lava)
    }

    /// Return the vanilla resource location for this block.
    pub fn block_name(&self) -> &'static str {
        match self {
            Self::Air => "minecraft:air",
            Self::Stone => "minecraft:stone",
            Self::Granite => "minecraft:granite",
            Self::Diorite => "minecraft:diorite",
            Self::Andesite => "minecraft:andesite",
            Self::Dirt => "minecraft:dirt",
            Self::CoarseDirt => "minecraft:coarse_dirt",
            Self::GrassBlock => "minecraft:grass_block",
            Self::Podzol => "minecraft:podzol",
            Self::Cobblestone => "minecraft:cobblestone",
            Self::Bedrock => "minecraft:bedrock",
            Self::Sand => "minecraft:sand",
            Self::RedSand => "minecraft:red_sand",
            Self::Gravel => "minecraft:gravel",
            Self::GoldOre => "minecraft:gold_ore",
            Self::IronOre => "minecraft:iron_ore",
            Self::CoalOre => "minecraft:coal_ore",
            Self::CopperOre => "minecraft:copper_ore",
            Self::DeepslateIronOre => "minecraft:deepslate_iron_ore",
            Self::DeepslateCoalOre => "minecraft:deepslate_coal_ore",
            Self::DeepslateGoldOre => "minecraft:deepslate_gold_ore",
            Self::DeepslateCopperOre => "minecraft:deepslate_copper_ore",
            Self::DeepslateDiamondOre => "minecraft:deepslate_diamond_ore",
            Self::DeepslateRedstoneOre => "minecraft:deepslate_redstone_ore",
            Self::DeepslateLapisOre => "minecraft:deepslate_lapis_ore",
            Self::DiamondOre => "minecraft:diamond_ore",
            Self::RedstoneOre => "minecraft:redstone_ore",
            Self::LapisOre => "minecraft:lapis_ore",
            Self::RawIronBlock => "minecraft:raw_iron_block",
            Self::RawCopperBlock => "minecraft:raw_copper_block",
            Self::OakLog => "minecraft:oak_log",
            Self::OakLeaves => "minecraft:oak_leaves",
            Self::Water => "minecraft:water",
            Self::Lava => "minecraft:lava",
            Self::Sandstone => "minecraft:sandstone",
            Self::RedSandstone => "minecraft:red_sandstone",
            Self::Ice => "minecraft:ice",
            Self::Snow => "minecraft:snow_block",
            Self::Clay => "minecraft:clay",
            Self::PackedIce => "minecraft:packed_ice",
            Self::PowderSnow => "minecraft:powder_snow",
            Self::BlueIce => "minecraft:blue_ice",
            Self::Terracotta => "minecraft:terracotta",
            Self::WhiteTerracotta => "minecraft:white_terracotta",
            Self::OrangeTerracotta => "minecraft:orange_terracotta",
            Self::BrownTerracotta => "minecraft:brown_terracotta",
            Self::BlackTerracotta => "minecraft:black_terracotta",
            Self::YellowTerracotta => "minecraft:yellow_terracotta",
            Self::RedTerracotta => "minecraft:red_terracotta",
            Self::LightGrayTerracotta => "minecraft:light_gray_terracotta",
            Self::Mud => "minecraft:mud",
            Self::Deepslate => "minecraft:deepslate",
            Self::Tuff => "minecraft:tuff",
            Self::Calcite => "minecraft:calcite",
            Self::Mycelium => "minecraft:mycelium",
            Self::Cinnabar => "minecraft:cinnabar",
            Self::Sulfur => "minecraft:sulfur",
            Self::Sculk => "minecraft:sculk",
            Self::SculkCatalyst => "minecraft:sculk_catalyst",
            Self::SculkVein => "minecraft:sculk_vein",
            Self::SculkSensor => "minecraft:sculk_sensor",
            Self::SculkShrieker => "minecraft:sculk_shrieker",
            Self::MossBlock => "minecraft:moss_block",
            Self::ShortGrass => "minecraft:short_grass",
            Self::LeafLitter => "minecraft:leaf_litter",
            Self::DarkOakLog => "minecraft:dark_oak_log",
            Self::DarkOakLeaves => "minecraft:dark_oak_leaves",
            Self::OakPlanks => "minecraft:oak_planks",
            Self::OakFence => "minecraft:oak_fence",
            Self::MossCarpet => "minecraft:moss_carpet",
            Self::CaveVinesPlant => "minecraft:cave_vines_plant",
            Self::CaveVines => "minecraft:cave_vines",
            Self::PaleOakLog => "minecraft:pale_oak_log",
            Self::PaleOakLeaves => "minecraft:pale_oak_leaves",
            Self::PaleMossBlock => "minecraft:pale_moss_block",
            Self::PaleMossCarpet => "minecraft:pale_moss_carpet",
            Self::Azalea => "minecraft:azalea",
            Self::FloweringAzalea => "minecraft:flowering_azalea",
            Self::HangingRoots => "minecraft:hanging_roots",
            Self::RootedDirt => "minecraft:rooted_dirt",
            Self::PaleHangingMoss => "minecraft:pale_hanging_moss",
            Self::CreakingHeart => "minecraft:creaking_heart",
        }
    }

    /// Parse a vanilla block name (`minecraft:grass_block`) to a BlockId.
    pub fn from_name(name: &str) -> Option<Self> {
        let n = name.strip_prefix("minecraft:").unwrap_or(name);
        match n {
            "air" | "cave_air" | "void_air" => Some(Self::Air),
            "stone" => Some(Self::Stone),
            "granite" => Some(Self::Granite),
            "diorite" => Some(Self::Diorite),
            "andesite" => Some(Self::Andesite),
            "dirt" => Some(Self::Dirt),
            "coarse_dirt" => Some(Self::CoarseDirt),
            "grass_block" => Some(Self::GrassBlock),
            "podzol" => Some(Self::Podzol),
            "mycelium" => Some(Self::Mycelium),
            "cobblestone" => Some(Self::Cobblestone),
            "sand" => Some(Self::Sand),
            "red_sand" => Some(Self::RedSand),
            "gravel" => Some(Self::Gravel),
            "gold_ore" => Some(Self::GoldOre),
            "iron_ore" => Some(Self::IronOre),
            "coal_ore" => Some(Self::CoalOre),
            "copper_ore" => Some(Self::CopperOre),
            "deepslate_iron_ore" => Some(Self::DeepslateIronOre),
            "deepslate_coal_ore" => Some(Self::DeepslateCoalOre),
            "deepslate_gold_ore" => Some(Self::DeepslateGoldOre),
            "deepslate_copper_ore" => Some(Self::DeepslateCopperOre),
            "deepslate_diamond_ore" => Some(Self::DeepslateDiamondOre),
            "deepslate_redstone_ore" => Some(Self::DeepslateRedstoneOre),
            "deepslate_lapis_ore" => Some(Self::DeepslateLapisOre),
            "diamond_ore" => Some(Self::DiamondOre),
            "redstone_ore" => Some(Self::RedstoneOre),
            "lapis_ore" => Some(Self::LapisOre),
            "raw_iron_block" => Some(Self::RawIronBlock),
            "raw_copper_block" => Some(Self::RawCopperBlock),
            "bedrock" => Some(Self::Bedrock),
            "water" => Some(Self::Water),
            "lava" => Some(Self::Lava),
            "sandstone" => Some(Self::Sandstone),
            "red_sandstone" => Some(Self::RedSandstone),
            "ice" => Some(Self::Ice),
            "snow_block" | "snow" => Some(Self::Snow),
            "clay" => Some(Self::Clay),
            "packed_ice" => Some(Self::PackedIce),
            "powder_snow" => Some(Self::PowderSnow),
            "terracotta" => Some(Self::Terracotta),
            "white_terracotta" => Some(Self::WhiteTerracotta),
            "orange_terracotta" => Some(Self::OrangeTerracotta),
            "brown_terracotta" => Some(Self::BrownTerracotta),
            "black_terracotta" => Some(Self::BlackTerracotta),
            "yellow_terracotta" => Some(Self::YellowTerracotta),
            "red_terracotta" => Some(Self::RedTerracotta),
            "light_gray_terracotta" => Some(Self::LightGrayTerracotta),
            "mud" => Some(Self::Mud),
            "deepslate" => Some(Self::Deepslate),
            "tuff" => Some(Self::Tuff),
            "calcite" => Some(Self::Calcite),
            "blue_ice" => Some(Self::BlueIce),
            "cinnabar" => Some(Self::Cinnabar),
            "sulfur" => Some(Self::Sulfur),
            "sculk" => Some(Self::Sculk),
            "sculk_catalyst" => Some(Self::SculkCatalyst),
            "sculk_vein" => Some(Self::SculkVein),
            "sculk_sensor" => Some(Self::SculkSensor),
            "sculk_shrieker" => Some(Self::SculkShrieker),
            "moss_block" => Some(Self::MossBlock),
            "short_grass" | "grass" | "tall_grass" => Some(Self::ShortGrass),
            "leaf_litter" => Some(Self::LeafLitter),
            "dark_oak_log" => Some(Self::DarkOakLog),
            "dark_oak_leaves" => Some(Self::DarkOakLeaves),
            "oak_log" => Some(Self::OakLog),
            "oak_leaves" => Some(Self::OakLeaves),
            "oak_planks" => Some(Self::OakPlanks),
            "oak_fence" => Some(Self::OakFence),
            "moss_carpet" => Some(Self::MossCarpet),
            "cave_vines_plant" => Some(Self::CaveVinesPlant),
            "cave_vines" => Some(Self::CaveVines),
            "pale_oak_log" => Some(Self::PaleOakLog),
            "pale_oak_leaves" => Some(Self::PaleOakLeaves),
            "pale_moss_block" => Some(Self::PaleMossBlock),
            "pale_moss_carpet" => Some(Self::PaleMossCarpet),
            "azalea" => Some(Self::Azalea),
            "flowering_azalea" => Some(Self::FloweringAzalea),
            "hanging_roots" => Some(Self::HangingRoots),
            "rooted_dirt" => Some(Self::RootedDirt),
            "pale_hanging_moss" => Some(Self::PaleHangingMoss),
            "creaking_heart" => Some(Self::CreakingHeart),
            _ => None,
        }
    }
}

/// Canonical vanilla block name for parity tooling (moved from block_parity example).
pub fn vanilla_name(b: BlockId) -> &'static str {
    match b {
        BlockId::Air => "minecraft:air",
        BlockId::Stone => "minecraft:stone",
        BlockId::Granite => "minecraft:granite",
        BlockId::Diorite => "minecraft:diorite",
        BlockId::Andesite => "minecraft:andesite",
        BlockId::Dirt => "minecraft:dirt",
        BlockId::CoarseDirt => "minecraft:coarse_dirt",
        BlockId::GrassBlock => "minecraft:grass_block",
        BlockId::Podzol => "minecraft:podzol",
        BlockId::Mycelium => "minecraft:mycelium",
        BlockId::Cobblestone => "minecraft:cobblestone",
        BlockId::Sand => "minecraft:sand",
        BlockId::RedSand => "minecraft:red_sand",
        BlockId::Gravel => "minecraft:gravel",
        BlockId::GoldOre => "minecraft:gold_ore",
        BlockId::IronOre => "minecraft:iron_ore",
        BlockId::CoalOre => "minecraft:coal_ore",
        BlockId::CopperOre => "minecraft:copper_ore",
        BlockId::DeepslateIronOre => "minecraft:deepslate_iron_ore",
        BlockId::DeepslateCoalOre => "minecraft:deepslate_coal_ore",
        BlockId::DeepslateGoldOre => "minecraft:deepslate_gold_ore",
        BlockId::DeepslateCopperOre => "minecraft:deepslate_copper_ore",
        BlockId::DeepslateDiamondOre => "minecraft:deepslate_diamond_ore",
        BlockId::DeepslateRedstoneOre => "minecraft:deepslate_redstone_ore",
        BlockId::DeepslateLapisOre => "minecraft:deepslate_lapis_ore",
        BlockId::DiamondOre => "minecraft:diamond_ore",
        BlockId::RedstoneOre => "minecraft:redstone_ore",
        BlockId::LapisOre => "minecraft:lapis_ore",
        BlockId::RawIronBlock => "minecraft:raw_iron_block",
        BlockId::RawCopperBlock => "minecraft:raw_copper_block",
        BlockId::Bedrock => "minecraft:bedrock",
        BlockId::OakLog => "minecraft:oak_log",
        BlockId::OakLeaves => "minecraft:oak_leaves",
        BlockId::Water => "minecraft:water",
        BlockId::Lava => "minecraft:lava",
        BlockId::Sandstone => "minecraft:sandstone",
        BlockId::RedSandstone => "minecraft:red_sandstone",
        BlockId::Ice => "minecraft:ice",
        BlockId::Snow => "minecraft:snow_block",
        BlockId::Clay => "minecraft:clay",
        BlockId::PackedIce => "minecraft:packed_ice",
        BlockId::PowderSnow => "minecraft:powder_snow",
        BlockId::Terracotta => "minecraft:terracotta",
        BlockId::WhiteTerracotta => "minecraft:white_terracotta",
        BlockId::OrangeTerracotta => "minecraft:orange_terracotta",
        BlockId::BrownTerracotta => "minecraft:brown_terracotta",
        BlockId::BlackTerracotta => "minecraft:black_terracotta",
        BlockId::YellowTerracotta => "minecraft:yellow_terracotta",
        BlockId::RedTerracotta => "minecraft:red_terracotta",
        BlockId::LightGrayTerracotta => "minecraft:light_gray_terracotta",
        BlockId::Mud => "minecraft:mud",
        BlockId::Deepslate => "minecraft:deepslate",
        BlockId::Tuff => "minecraft:tuff",
        BlockId::Calcite => "minecraft:calcite",
        BlockId::BlueIce => "minecraft:blue_ice",
        BlockId::Cinnabar => "minecraft:cinnabar",
        BlockId::Sulfur => "minecraft:sulfur",
        BlockId::Sculk => "minecraft:sculk",
        BlockId::SculkCatalyst => "minecraft:sculk_catalyst",
        BlockId::SculkVein => "minecraft:sculk_vein",
        BlockId::SculkSensor => "minecraft:sculk_sensor",
        BlockId::SculkShrieker => "minecraft:sculk_shrieker",
        BlockId::MossBlock => "minecraft:moss_block",
        BlockId::ShortGrass => "minecraft:short_grass",
        BlockId::LeafLitter => "minecraft:leaf_litter",
        BlockId::DarkOakLog => "minecraft:dark_oak_log",
        BlockId::DarkOakLeaves => "minecraft:dark_oak_leaves",
        BlockId::OakPlanks => "minecraft:oak_planks",
        BlockId::OakFence => "minecraft:oak_fence",
        BlockId::MossCarpet => "minecraft:moss_carpet",
        BlockId::CaveVinesPlant => "minecraft:cave_vines_plant",
        BlockId::CaveVines => "minecraft:cave_vines",
        BlockId::PaleOakLog => "minecraft:pale_oak_log",
        BlockId::PaleOakLeaves => "minecraft:pale_oak_leaves",
        BlockId::PaleMossBlock => "minecraft:pale_moss_block",
        BlockId::PaleMossCarpet => "minecraft:pale_moss_carpet",
        BlockId::Azalea => "minecraft:azalea",
        BlockId::FloweringAzalea => "minecraft:flowering_azalea",
        BlockId::HangingRoots => "minecraft:hanging_roots",
        BlockId::RootedDirt => "minecraft:rooted_dirt",
        BlockId::PaleHangingMoss => "minecraft:pale_hanging_moss",
        BlockId::CreakingHeart => "minecraft:creaking_heart",
    }
}

/// Vegetation classifier for BASE (no-veg) parity (moved from block_parity example).
pub fn is_vegetation_name(name: &str) -> bool {
    is_veg(name)
}

fn is_veg(name: &str) -> bool {
    let n = name.strip_prefix("minecraft:").unwrap_or(name);
    n.contains("leaves")
        || n.contains("log")
        || n.contains("wood")
        || n == "leaf_litter"
        || n == "vine"
        || n == "short_grass"
        || n == "tall_grass"
        || n == "grass"
        || n == "fern"
        || n == "large_fern"
        || n.contains("orchid")
        || n.contains("tulip")
        || n.contains("daisy")
        || n.contains("lilac")
        || n.contains("rose")
        || n.contains("peony")
        || n.contains("azalea")
        || n.contains("mushroom")
        || n == "dandelion"
        || n == "poppy"
        || n == "cornflower"
        || n == "oxeye_daisy"
        || n == "lily_of_the_valley"
        || n == "pink_petals"
        || n == "moss_carpet"
        || n == "moss_block"
        || n == "pale_moss_block"
        || n == "pale_moss_carpet"
        || n == "sculk"
        || n == "sculk_vein"
        || n == "sculk_sensor"
        || n == "sculk_catalyst"
        || n == "sculk_shrieker"
        || n == "glow_lichen"
        || n.contains("sapling")
        || n == "cave_vines"
        || n == "cave_vines_plant"
        || n == "hanging_roots"
        || n == "rooted_dirt"
        || n == "spore_blossom"
}
