//! Internal worldgen block IDs stored in [`GeneratedChunk::blocks`](crate::GeneratedChunk).
//!
//! Compact `u16` values, **not** protocol state IDs. The server remaps them
//! in `neutron-server::protocol_data`. The parity tool maps names for NBT.
//!
//! Copyright (c) 2026 Neutron Contributors -- MIT License

/// Minecraft block IDs used during chunk generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    Granite = 2,
    Diorite = 3,
    Andesite = 4,
    Dirt = 10,
    CoarseDirt = 11,
    GrassBlock = 12,
    Podzol = 14,
    Mycelium = 15,
    Cobblestone = 20,
    Sand = 24,
    RedSand = 25,
    Gravel = 26,
    GoldOre = 27,
    IronOre = 28,
    CoalOre = 29,
    CopperOre = 30,
    DeepslateIronOre = 31,
    RawIronBlock = 32,
    Bedrock = 33,
    RawCopperBlock = 34,
    DeepslateCoalOre = 35,
    DeepslateGoldOre = 36,
    DeepslateCopperOre = 37,
    DeepslateDiamondOre = 38,
    DeepslateRedstoneOre = 39,
    DeepslateLapisOre = 42,
    DiamondOre = 43,
    RedstoneOre = 44,
    LapisOre = 45,
    OakLog = 40,
    OakLeaves = 41,
    Water = 50,
    Lava = 51,
    Sandstone = 52,
    RedSandstone = 53,
    Ice = 54,
    Snow = 55,
    Clay = 56,
    PackedIce = 57,
    PowderSnow = 58,
    Terracotta = 59,
    WhiteTerracotta = 60,
    OrangeTerracotta = 61,
    BrownTerracotta = 62,
    BlackTerracotta = 63,
    Mud = 64,
    Deepslate = 65,
    Tuff = 66,
    Calcite = 67,
    BlueIce = 68,
    YellowTerracotta = 69,
    RedTerracotta = 70,
    LightGrayTerracotta = 71,
    /// Placeholder for 26.2 sulfur caves until palette is expanded.
    Cinnabar = 72,
    Sulfur = 73,
    Sculk = 74,
    SculkCatalyst = 75,
    SculkVein = 76,
    SculkSensor = 77,
    SculkShrieker = 78,
    MossBlock = 79,
    ShortGrass = 80,
    /// Surface leaf litter (1.21+).
    LeafLitter = 81,
    DarkOakLog = 82,
    DarkOakLeaves = 83,
    OakPlanks = 84,
    OakFence = 85,
    MossCarpet = 86,
    CaveVinesPlant = 87,
    CaveVines = 88,
    PaleOakLog = 89,
    PaleOakLeaves = 90,
    PaleMossBlock = 91,
    PaleMossCarpet = 92,
    Azalea = 93,
    FloweringAzalea = 94,
    HangingRoots = 95,
    RootedDirt = 96,
    PaleHangingMoss = 97,
    CreakingHeart = 98,
    GlowLichen = 99,
    Vine = 100,
    BirchLog = 101,
    BirchLeaves = 102,
    SpruceLog = 103,
    SpruceLeaves = 104,
    JungleLog = 105,
    JungleLeaves = 106,
    AcaciaLog = 107,
    AcaciaLeaves = 108,
    MangroveLog = 109,
    MangroveLeaves = 110,
    CherryLog = 111,
    CherryLeaves = 112,
    SeaPickle = 113,
    Seagrass = 114,
    TallSeagrass = 115,
    Kelp = 116,
    KelpPlant = 117,
    MossyCobblestone = 118,
    /// T4 ports (run-058): desert_well / bamboo / dripstone / geode / fossil / ice.
    SandstoneSlab = 119,
    SuspiciousSand = 120,
    DripstoneBlock = 121,
    PointedDripstone = 122,
    SulfurSpike = 123,
    PotentSulfur = 124,
    BoneBlock = 125,
    Chest = 126,
    Spawner = 127,
    Bamboo = 128,
    AmethystBlock = 129,
    BuddingAmethyst = 130,
    SmoothBasalt = 131,
    SmallAmethystBud = 132,
    MediumAmethystBud = 133,
    LargeAmethystBud = 134,
    AmethystCluster = 135,
    SmallDripleaf = 136,
    BigDripleaf = 137,
    BigDripleafStem = 138,
    /// Mineshaft / monster-room / lake "air" (`Blocks.CAVE_AIR`). Behaves as
    /// air everywhere (`is_air`, heightmaps, placement gates).
    CaveAir = 139,
    /// Double tall grass (`Blocks.TALL_GRASS`, lower+upper halves share the
    /// block id — the half property is not modeled; parity compares names).
    TallGrass = 140,
    /// pale_moss_carpet TOPPER layer (`BASE=false`, no collision). Same vanilla
    /// block name as [`BlockId::PaleMossCarpet`] (which models the BASE layer);
    /// the split exists so MossyCarpetBlock.placeAt's stacking gate and topper
    /// dice match vanilla when carpets pile up.
    PaleMossCarpetTopper = 141,
    /// Huge mushroom caps/stems (`HugeRedMushroomFeature`). Properties
    /// (WEST/EAST/NORTH/SOUTH/UP faces) are not modeled; parity compares ids.
    RedMushroomBlock = 142,
    BrownMushroomBlock = 143,
    MushroomStem = 144,
}

impl BlockId {
    pub fn as_u16(self) -> u16 {
        self as u16
    }

    pub fn from_u16(v: u16) -> Option<Self> {
        match v {
            0 => Some(Self::Air),
            1 => Some(Self::Stone),
            2 => Some(Self::Granite),
            3 => Some(Self::Diorite),
            4 => Some(Self::Andesite),
            10 => Some(Self::Dirt),
            11 => Some(Self::CoarseDirt),
            12 => Some(Self::GrassBlock),
            14 => Some(Self::Podzol),
            15 => Some(Self::Mycelium),
            20 => Some(Self::Cobblestone),
            24 => Some(Self::Sand),
            25 => Some(Self::RedSand),
            26 => Some(Self::Gravel),
            27 => Some(Self::GoldOre),
            28 => Some(Self::IronOre),
            29 => Some(Self::CoalOre),
            30 => Some(Self::CopperOre),
            31 => Some(Self::DeepslateIronOre),
            32 => Some(Self::RawIronBlock),
            33 => Some(Self::Bedrock),
            34 => Some(Self::RawCopperBlock),
            35 => Some(Self::DeepslateCoalOre),
            36 => Some(Self::DeepslateGoldOre),
            37 => Some(Self::DeepslateCopperOre),
            38 => Some(Self::DeepslateDiamondOre),
            39 => Some(Self::DeepslateRedstoneOre),
            40 => Some(Self::OakLog),
            41 => Some(Self::OakLeaves),
            42 => Some(Self::DeepslateLapisOre),
            43 => Some(Self::DiamondOre),
            44 => Some(Self::RedstoneOre),
            45 => Some(Self::LapisOre),
            50 => Some(Self::Water),
            51 => Some(Self::Lava),
            52 => Some(Self::Sandstone),
            53 => Some(Self::RedSandstone),
            54 => Some(Self::Ice),
            55 => Some(Self::Snow),
            56 => Some(Self::Clay),
            57 => Some(Self::PackedIce),
            58 => Some(Self::PowderSnow),
            59 => Some(Self::Terracotta),
            60 => Some(Self::WhiteTerracotta),
            61 => Some(Self::OrangeTerracotta),
            62 => Some(Self::BrownTerracotta),
            63 => Some(Self::BlackTerracotta),
            64 => Some(Self::Mud),
            65 => Some(Self::Deepslate),
            66 => Some(Self::Tuff),
            67 => Some(Self::Calcite),
            68 => Some(Self::BlueIce),
            69 => Some(Self::YellowTerracotta),
            70 => Some(Self::RedTerracotta),
            71 => Some(Self::LightGrayTerracotta),
            72 => Some(Self::Cinnabar),
            73 => Some(Self::Sulfur),
            74 => Some(Self::Sculk),
            75 => Some(Self::SculkCatalyst),
            76 => Some(Self::SculkVein),
            77 => Some(Self::SculkSensor),
            78 => Some(Self::SculkShrieker),
            79 => Some(Self::MossBlock),
            80 => Some(Self::ShortGrass),
            81 => Some(Self::LeafLitter),
            82 => Some(Self::DarkOakLog),
            83 => Some(Self::DarkOakLeaves),
            84 => Some(Self::OakPlanks),
            85 => Some(Self::OakFence),
            86 => Some(Self::MossCarpet),
            87 => Some(Self::CaveVinesPlant),
            88 => Some(Self::CaveVines),
            89 => Some(Self::PaleOakLog),
            90 => Some(Self::PaleOakLeaves),
            91 => Some(Self::PaleMossBlock),
            92 => Some(Self::PaleMossCarpet),
            93 => Some(Self::Azalea),
            94 => Some(Self::FloweringAzalea),
            95 => Some(Self::HangingRoots),
            96 => Some(Self::RootedDirt),
            97 => Some(Self::PaleHangingMoss),
            98 => Some(Self::CreakingHeart),
            99 => Some(Self::GlowLichen),
            100 => Some(Self::Vine),
            101 => Some(Self::BirchLog),
            102 => Some(Self::BirchLeaves),
            103 => Some(Self::SpruceLog),
            104 => Some(Self::SpruceLeaves),
            105 => Some(Self::JungleLog),
            106 => Some(Self::JungleLeaves),
            107 => Some(Self::AcaciaLog),
            108 => Some(Self::AcaciaLeaves),
            109 => Some(Self::MangroveLog),
            110 => Some(Self::MangroveLeaves),
            111 => Some(Self::CherryLog),
            112 => Some(Self::CherryLeaves),
            113 => Some(Self::SeaPickle),
            114 => Some(Self::Seagrass),
            115 => Some(Self::TallSeagrass),
            116 => Some(Self::Kelp),
            117 => Some(Self::KelpPlant),
            118 => Some(Self::MossyCobblestone),
            119 => Some(Self::SandstoneSlab),
            120 => Some(Self::SuspiciousSand),
            121 => Some(Self::DripstoneBlock),
            122 => Some(Self::PointedDripstone),
            123 => Some(Self::SulfurSpike),
            124 => Some(Self::PotentSulfur),
            125 => Some(Self::BoneBlock),
            126 => Some(Self::Chest),
            127 => Some(Self::Spawner),
            128 => Some(Self::Bamboo),
            129 => Some(Self::AmethystBlock),
            130 => Some(Self::BuddingAmethyst),
            131 => Some(Self::SmoothBasalt),
            132 => Some(Self::SmallAmethystBud),
            133 => Some(Self::MediumAmethystBud),
            134 => Some(Self::LargeAmethystBud),
            135 => Some(Self::AmethystCluster),
            136 => Some(Self::SmallDripleaf),
            137 => Some(Self::BigDripleaf),
            138 => Some(Self::BigDripleafStem),
            139 => Some(Self::CaveAir),
            140 => Some(Self::TallGrass),
            141 => Some(Self::PaleMossCarpetTopper),
            142 => Some(Self::RedMushroomBlock),
            143 => Some(Self::BrownMushroomBlock),
            144 => Some(Self::MushroomStem),
            _ => None,
        }
    }

    pub fn is_air(self) -> bool {
        matches!(self, Self::Air | Self::CaveAir)
    }

    pub fn is_fluid(self) -> bool {
        matches!(self, Self::Water | Self::Lava)
    }

    /// Return the vanilla resource location for this block.
    pub fn block_name(&self) -> &'static str {
        match self {
            Self::Air => "minecraft:air",
            Self::CaveAir => "minecraft:cave_air",
            Self::TallGrass => "minecraft:tall_grass",
            Self::PaleMossCarpet | Self::PaleMossCarpetTopper => "minecraft:pale_moss_carpet",
            Self::RedMushroomBlock => "minecraft:red_mushroom_block",
            Self::BrownMushroomBlock => "minecraft:brown_mushroom_block",
            Self::MushroomStem => "minecraft:mushroom_stem",
            Self::Stone => "minecraft:stone",
            Self::Granite => "minecraft:granite",
            Self::Diorite => "minecraft:diorite",
            Self::Andesite => "minecraft:andesite",
            Self::Dirt => "minecraft:dirt",
            Self::CoarseDirt => "minecraft:coarse_dirt",
            Self::GrassBlock => "minecraft:grass_block",
            Self::Podzol => "minecraft:podzol",
            Self::Cobblestone => "minecraft:cobblestone",
            Self::Bedrock => "minecraft:bedrock",
            Self::Sand => "minecraft:sand",
            Self::RedSand => "minecraft:red_sand",
            Self::Gravel => "minecraft:gravel",
            Self::GoldOre => "minecraft:gold_ore",
            Self::IronOre => "minecraft:iron_ore",
            Self::CoalOre => "minecraft:coal_ore",
            Self::CopperOre => "minecraft:copper_ore",
            Self::DeepslateIronOre => "minecraft:deepslate_iron_ore",
            Self::DeepslateCoalOre => "minecraft:deepslate_coal_ore",
            Self::DeepslateGoldOre => "minecraft:deepslate_gold_ore",
            Self::DeepslateCopperOre => "minecraft:deepslate_copper_ore",
            Self::DeepslateDiamondOre => "minecraft:deepslate_diamond_ore",
            Self::DeepslateRedstoneOre => "minecraft:deepslate_redstone_ore",
            Self::DeepslateLapisOre => "minecraft:deepslate_lapis_ore",
            Self::DiamondOre => "minecraft:diamond_ore",
            Self::RedstoneOre => "minecraft:redstone_ore",
            Self::LapisOre => "minecraft:lapis_ore",
            Self::RawIronBlock => "minecraft:raw_iron_block",
            Self::RawCopperBlock => "minecraft:raw_copper_block",
            Self::OakLog => "minecraft:oak_log",
            Self::OakLeaves => "minecraft:oak_leaves",
            Self::Water => "minecraft:water",
            Self::Lava => "minecraft:lava",
            Self::Sandstone => "minecraft:sandstone",
            Self::RedSandstone => "minecraft:red_sandstone",
            Self::Ice => "minecraft:ice",
            Self::Snow => "minecraft:snow_block",
            Self::Clay => "minecraft:clay",
            Self::PackedIce => "minecraft:packed_ice",
            Self::PowderSnow => "minecraft:powder_snow",
            Self::BlueIce => "minecraft:blue_ice",
            Self::Terracotta => "minecraft:terracotta",
            Self::WhiteTerracotta => "minecraft:white_terracotta",
            Self::OrangeTerracotta => "minecraft:orange_terracotta",
            Self::BrownTerracotta => "minecraft:brown_terracotta",
            Self::BlackTerracotta => "minecraft:black_terracotta",
            Self::YellowTerracotta => "minecraft:yellow_terracotta",
            Self::RedTerracotta => "minecraft:red_terracotta",
            Self::LightGrayTerracotta => "minecraft:light_gray_terracotta",
            Self::Mud => "minecraft:mud",
            Self::Deepslate => "minecraft:deepslate",
            Self::Tuff => "minecraft:tuff",
            Self::Calcite => "minecraft:calcite",
            Self::Mycelium => "minecraft:mycelium",
            Self::Cinnabar => "minecraft:cinnabar",
            Self::Sulfur => "minecraft:sulfur",
            Self::Sculk => "minecraft:sculk",
            Self::SculkCatalyst => "minecraft:sculk_catalyst",
            Self::SculkVein => "minecraft:sculk_vein",
            Self::SculkSensor => "minecraft:sculk_sensor",
            Self::SculkShrieker => "minecraft:sculk_shrieker",
            Self::MossBlock => "minecraft:moss_block",
            Self::ShortGrass => "minecraft:short_grass",
            Self::LeafLitter => "minecraft:leaf_litter",
            Self::DarkOakLog => "minecraft:dark_oak_log",
            Self::DarkOakLeaves => "minecraft:dark_oak_leaves",
            Self::OakPlanks => "minecraft:oak_planks",
            Self::OakFence => "minecraft:oak_fence",
            Self::MossCarpet => "minecraft:moss_carpet",
            Self::CaveVinesPlant => "minecraft:cave_vines_plant",
            Self::CaveVines => "minecraft:cave_vines",
            Self::PaleOakLog => "minecraft:pale_oak_log",
            Self::PaleOakLeaves => "minecraft:pale_oak_leaves",
            Self::PaleMossBlock => "minecraft:pale_moss_block",
            Self::PaleMossCarpet => "minecraft:pale_moss_carpet",
            Self::Azalea => "minecraft:azalea",
            Self::FloweringAzalea => "minecraft:flowering_azalea",
            Self::HangingRoots => "minecraft:hanging_roots",
            Self::RootedDirt => "minecraft:rooted_dirt",
            Self::PaleHangingMoss => "minecraft:pale_hanging_moss",
            Self::CreakingHeart => "minecraft:creaking_heart",
            Self::GlowLichen => "minecraft:glow_lichen",
            Self::Vine => "minecraft:vine",
            Self::BirchLog => "minecraft:birch_log",
            Self::BirchLeaves => "minecraft:birch_leaves",
            Self::SpruceLog => "minecraft:spruce_log",
            Self::SpruceLeaves => "minecraft:spruce_leaves",
            Self::JungleLog => "minecraft:jungle_log",
            Self::JungleLeaves => "minecraft:jungle_leaves",
            Self::AcaciaLog => "minecraft:acacia_log",
            Self::AcaciaLeaves => "minecraft:acacia_leaves",
            Self::MangroveLog => "minecraft:mangrove_log",
            Self::MangroveLeaves => "minecraft:mangrove_leaves",
            Self::CherryLog => "minecraft:cherry_log",
            Self::CherryLeaves => "minecraft:cherry_leaves",
            Self::SeaPickle => "minecraft:sea_pickle",
            Self::Seagrass => "minecraft:seagrass",
            Self::TallSeagrass => "minecraft:tall_seagrass",
            Self::Kelp => "minecraft:kelp",
            Self::KelpPlant => "minecraft:kelp_plant",
            Self::MossyCobblestone => "minecraft:mossy_cobblestone",
            Self::SandstoneSlab => "minecraft:sandstone_slab",
            Self::SuspiciousSand => "minecraft:suspicious_sand",
            Self::DripstoneBlock => "minecraft:dripstone_block",
            Self::PointedDripstone => "minecraft:pointed_dripstone",
            Self::SulfurSpike => "minecraft:sulfur_spike",
            Self::PotentSulfur => "minecraft:potent_sulfur",
            Self::BoneBlock => "minecraft:bone_block",
            Self::Chest => "minecraft:chest",
            Self::Spawner => "minecraft:spawner",
            Self::Bamboo => "minecraft:bamboo",
            Self::AmethystBlock => "minecraft:amethyst_block",
            Self::BuddingAmethyst => "minecraft:budding_amethyst",
            Self::SmoothBasalt => "minecraft:smooth_basalt",
            Self::SmallAmethystBud => "minecraft:small_amethyst_bud",
            Self::MediumAmethystBud => "minecraft:medium_amethyst_bud",
            Self::LargeAmethystBud => "minecraft:large_amethyst_bud",
            Self::AmethystCluster => "minecraft:amethyst_cluster",
            Self::SmallDripleaf => "minecraft:small_dripleaf",
            Self::BigDripleaf => "minecraft:big_dripleaf",
            Self::BigDripleafStem => "minecraft:big_dripleaf_stem",
        }
    }

    /// Parse a vanilla block name (`minecraft:grass_block`) to a BlockId.
    pub fn from_name(name: &str) -> Option<Self> {
        let n = name.strip_prefix("minecraft:").unwrap_or(name);
        match n {
            "air" | "void_air" => Some(Self::Air),
            "cave_air" => Some(Self::CaveAir),
            "stone" => Some(Self::Stone),
            "granite" => Some(Self::Granite),
            "diorite" => Some(Self::Diorite),
            "andesite" => Some(Self::Andesite),
            "dirt" => Some(Self::Dirt),
            "coarse_dirt" => Some(Self::CoarseDirt),
            "grass_block" => Some(Self::GrassBlock),
            "podzol" => Some(Self::Podzol),
            "mycelium" => Some(Self::Mycelium),
            "cobblestone" => Some(Self::Cobblestone),
            "sand" => Some(Self::Sand),
            "red_sand" => Some(Self::RedSand),
            "gravel" => Some(Self::Gravel),
            "gold_ore" => Some(Self::GoldOre),
            "iron_ore" => Some(Self::IronOre),
            "coal_ore" => Some(Self::CoalOre),
            "copper_ore" => Some(Self::CopperOre),
            "deepslate_iron_ore" => Some(Self::DeepslateIronOre),
            "deepslate_coal_ore" => Some(Self::DeepslateCoalOre),
            "deepslate_gold_ore" => Some(Self::DeepslateGoldOre),
            "deepslate_copper_ore" => Some(Self::DeepslateCopperOre),
            "deepslate_diamond_ore" => Some(Self::DeepslateDiamondOre),
            "deepslate_redstone_ore" => Some(Self::DeepslateRedstoneOre),
            "deepslate_lapis_ore" => Some(Self::DeepslateLapisOre),
            "diamond_ore" => Some(Self::DiamondOre),
            "redstone_ore" => Some(Self::RedstoneOre),
            "lapis_ore" => Some(Self::LapisOre),
            "raw_iron_block" => Some(Self::RawIronBlock),
            "raw_copper_block" => Some(Self::RawCopperBlock),
            "bedrock" => Some(Self::Bedrock),
            "water" => Some(Self::Water),
            "lava" => Some(Self::Lava),
            "sandstone" => Some(Self::Sandstone),
            "red_sandstone" => Some(Self::RedSandstone),
            "ice" => Some(Self::Ice),
            "snow_block" | "snow" => Some(Self::Snow),
            "clay" => Some(Self::Clay),
            "packed_ice" => Some(Self::PackedIce),
            "powder_snow" => Some(Self::PowderSnow),
            "terracotta" => Some(Self::Terracotta),
            "white_terracotta" => Some(Self::WhiteTerracotta),
            "orange_terracotta" => Some(Self::OrangeTerracotta),
            "brown_terracotta" => Some(Self::BrownTerracotta),
            "black_terracotta" => Some(Self::BlackTerracotta),
            "yellow_terracotta" => Some(Self::YellowTerracotta),
            "red_terracotta" => Some(Self::RedTerracotta),
            "light_gray_terracotta" => Some(Self::LightGrayTerracotta),
            "mud" => Some(Self::Mud),
            "deepslate" => Some(Self::Deepslate),
            "tuff" => Some(Self::Tuff),
            "calcite" => Some(Self::Calcite),
            "blue_ice" => Some(Self::BlueIce),
            "cinnabar" => Some(Self::Cinnabar),
            "sulfur" => Some(Self::Sulfur),
            "sculk" => Some(Self::Sculk),
            "sculk_catalyst" => Some(Self::SculkCatalyst),
            "sculk_vein" => Some(Self::SculkVein),
            "sculk_sensor" => Some(Self::SculkSensor),
            "sculk_shrieker" => Some(Self::SculkShrieker),
            "moss_block" => Some(Self::MossBlock),
            "short_grass" | "grass" => Some(Self::ShortGrass),
            "tall_grass" => Some(Self::TallGrass),
            "leaf_litter" => Some(Self::LeafLitter),
            "dark_oak_log" => Some(Self::DarkOakLog),
            "dark_oak_leaves" => Some(Self::DarkOakLeaves),
            "oak_log" => Some(Self::OakLog),
            "oak_leaves" => Some(Self::OakLeaves),
            "oak_planks" => Some(Self::OakPlanks),
            "oak_fence" => Some(Self::OakFence),
            "moss_carpet" => Some(Self::MossCarpet),
            "cave_vines_plant" => Some(Self::CaveVinesPlant),
            "cave_vines" => Some(Self::CaveVines),
            "pale_oak_log" => Some(Self::PaleOakLog),
            "pale_oak_leaves" => Some(Self::PaleOakLeaves),
            "pale_moss_block" => Some(Self::PaleMossBlock),
            "pale_moss_carpet" => Some(Self::PaleMossCarpet),
            "azalea" => Some(Self::Azalea),
            "flowering_azalea" => Some(Self::FloweringAzalea),
            "hanging_roots" => Some(Self::HangingRoots),
            "rooted_dirt" => Some(Self::RootedDirt),
            "pale_hanging_moss" => Some(Self::PaleHangingMoss),
            "creaking_heart" => Some(Self::CreakingHeart),
            "glow_lichen" => Some(Self::GlowLichen),
            "vine" => Some(Self::Vine),
            "birch_log" => Some(Self::BirchLog),
            "birch_leaves" => Some(Self::BirchLeaves),
            "spruce_log" => Some(Self::SpruceLog),
            "spruce_leaves" => Some(Self::SpruceLeaves),
            "jungle_log" => Some(Self::JungleLog),
            "jungle_leaves" => Some(Self::JungleLeaves),
            "acacia_log" => Some(Self::AcaciaLog),
            "acacia_leaves" => Some(Self::AcaciaLeaves),
            "mangrove_log" => Some(Self::MangroveLog),
            "mangrove_leaves" => Some(Self::MangroveLeaves),
            "cherry_log" => Some(Self::CherryLog),
            "cherry_leaves" => Some(Self::CherryLeaves),
            "sea_pickle" => Some(Self::SeaPickle),
            "seagrass" => Some(Self::Seagrass),
            "tall_seagrass" => Some(Self::TallSeagrass),
            "kelp" => Some(Self::Kelp),
            "kelp_plant" => Some(Self::KelpPlant),
            "mossy_cobblestone" => Some(Self::MossyCobblestone),
            "sandstone_slab" => Some(Self::SandstoneSlab),
            "suspicious_sand" => Some(Self::SuspiciousSand),
            "dripstone_block" => Some(Self::DripstoneBlock),
            "pointed_dripstone" => Some(Self::PointedDripstone),
            "sulfur_spike" => Some(Self::SulfurSpike),
            "potent_sulfur" => Some(Self::PotentSulfur),
            "bone_block" => Some(Self::BoneBlock),
            "chest" => Some(Self::Chest),
            "spawner" => Some(Self::Spawner),
            "bamboo" => Some(Self::Bamboo),
            "amethyst_block" => Some(Self::AmethystBlock),
            "budding_amethyst" => Some(Self::BuddingAmethyst),
            "smooth_basalt" => Some(Self::SmoothBasalt),
            "small_amethyst_bud" => Some(Self::SmallAmethystBud),
            "medium_amethyst_bud" => Some(Self::MediumAmethystBud),
            "large_amethyst_bud" => Some(Self::LargeAmethystBud),
            "amethyst_cluster" => Some(Self::AmethystCluster),
            "small_dripleaf" => Some(Self::SmallDripleaf),
            "big_dripleaf" => Some(Self::BigDripleaf),
            "big_dripleaf_stem" => Some(Self::BigDripleafStem),
            // Infested variants are visually identical to their host block.
            "infested_stone" => Some(Self::Stone),
            "infested_cobblestone" => Some(Self::Cobblestone),
            "infested_deepslate" => Some(Self::Deepslate),
            _ => None,
        }
    }
}

/// Canonical vanilla block name for parity tooling (moved from block_parity example).
pub fn vanilla_name(b: BlockId) -> &'static str {
    match b {
        BlockId::Air => "minecraft:air",
        BlockId::Stone => "minecraft:stone",
        BlockId::Granite => "minecraft:granite",
        BlockId::Diorite => "minecraft:diorite",
        BlockId::Andesite => "minecraft:andesite",
        BlockId::Dirt => "minecraft:dirt",
        BlockId::CoarseDirt => "minecraft:coarse_dirt",
        BlockId::GrassBlock => "minecraft:grass_block",
        BlockId::Podzol => "minecraft:podzol",
        BlockId::Mycelium => "minecraft:mycelium",
        BlockId::Cobblestone => "minecraft:cobblestone",
        BlockId::Sand => "minecraft:sand",
        BlockId::RedSand => "minecraft:red_sand",
        BlockId::Gravel => "minecraft:gravel",
        BlockId::GoldOre => "minecraft:gold_ore",
        BlockId::IronOre => "minecraft:iron_ore",
        BlockId::CoalOre => "minecraft:coal_ore",
        BlockId::CopperOre => "minecraft:copper_ore",
        BlockId::DeepslateIronOre => "minecraft:deepslate_iron_ore",
        BlockId::DeepslateCoalOre => "minecraft:deepslate_coal_ore",
        BlockId::DeepslateGoldOre => "minecraft:deepslate_gold_ore",
        BlockId::DeepslateCopperOre => "minecraft:deepslate_copper_ore",
        BlockId::DeepslateDiamondOre => "minecraft:deepslate_diamond_ore",
        BlockId::DeepslateRedstoneOre => "minecraft:deepslate_redstone_ore",
        BlockId::DeepslateLapisOre => "minecraft:deepslate_lapis_ore",
        BlockId::DiamondOre => "minecraft:diamond_ore",
        BlockId::RedstoneOre => "minecraft:redstone_ore",
        BlockId::LapisOre => "minecraft:lapis_ore",
        BlockId::RawIronBlock => "minecraft:raw_iron_block",
        BlockId::RawCopperBlock => "minecraft:raw_copper_block",
        BlockId::Bedrock => "minecraft:bedrock",
        BlockId::OakLog => "minecraft:oak_log",
        BlockId::OakLeaves => "minecraft:oak_leaves",
        BlockId::Water => "minecraft:water",
        BlockId::Lava => "minecraft:lava",
        BlockId::Sandstone => "minecraft:sandstone",
        BlockId::RedSandstone => "minecraft:red_sandstone",
        BlockId::Ice => "minecraft:ice",
        BlockId::Snow => "minecraft:snow_block",
        BlockId::Clay => "minecraft:clay",
        BlockId::PackedIce => "minecraft:packed_ice",
        BlockId::PowderSnow => "minecraft:powder_snow",
        BlockId::Terracotta => "minecraft:terracotta",
        BlockId::WhiteTerracotta => "minecraft:white_terracotta",
        BlockId::OrangeTerracotta => "minecraft:orange_terracotta",
        BlockId::BrownTerracotta => "minecraft:brown_terracotta",
        BlockId::BlackTerracotta => "minecraft:black_terracotta",
        BlockId::YellowTerracotta => "minecraft:yellow_terracotta",
        BlockId::RedTerracotta => "minecraft:red_terracotta",
        BlockId::LightGrayTerracotta => "minecraft:light_gray_terracotta",
        BlockId::Mud => "minecraft:mud",
        BlockId::Deepslate => "minecraft:deepslate",
        BlockId::Tuff => "minecraft:tuff",
        BlockId::Calcite => "minecraft:calcite",
        BlockId::BlueIce => "minecraft:blue_ice",
        BlockId::Cinnabar => "minecraft:cinnabar",
        BlockId::Sulfur => "minecraft:sulfur",
        BlockId::Sculk => "minecraft:sculk",
        BlockId::SculkCatalyst => "minecraft:sculk_catalyst",
        BlockId::SculkVein => "minecraft:sculk_vein",
        BlockId::SculkSensor => "minecraft:sculk_sensor",
        BlockId::SculkShrieker => "minecraft:sculk_shrieker",
        BlockId::MossBlock => "minecraft:moss_block",
        BlockId::ShortGrass => "minecraft:short_grass",
        BlockId::LeafLitter => "minecraft:leaf_litter",
        BlockId::DarkOakLog => "minecraft:dark_oak_log",
        BlockId::DarkOakLeaves => "minecraft:dark_oak_leaves",
        BlockId::OakPlanks => "minecraft:oak_planks",
        BlockId::OakFence => "minecraft:oak_fence",
        BlockId::MossCarpet => "minecraft:moss_carpet",
        BlockId::CaveVinesPlant => "minecraft:cave_vines_plant",
        BlockId::CaveVines => "minecraft:cave_vines",
        BlockId::PaleOakLog => "minecraft:pale_oak_log",
        BlockId::PaleOakLeaves => "minecraft:pale_oak_leaves",
        BlockId::PaleMossBlock => "minecraft:pale_moss_block",
        BlockId::PaleMossCarpet => "minecraft:pale_moss_carpet",
        BlockId::Azalea => "minecraft:azalea",
        BlockId::FloweringAzalea => "minecraft:flowering_azalea",
        BlockId::HangingRoots => "minecraft:hanging_roots",
        BlockId::RootedDirt => "minecraft:rooted_dirt",
        BlockId::PaleHangingMoss => "minecraft:pale_hanging_moss",
        BlockId::CreakingHeart => "minecraft:creaking_heart",
        BlockId::GlowLichen => "minecraft:glow_lichen",
        BlockId::Vine => "minecraft:vine",
        BlockId::BirchLog => "minecraft:birch_log",
        BlockId::BirchLeaves => "minecraft:birch_leaves",
        BlockId::SpruceLog => "minecraft:spruce_log",
        BlockId::SpruceLeaves => "minecraft:spruce_leaves",
        BlockId::JungleLog => "minecraft:jungle_log",
        BlockId::JungleLeaves => "minecraft:jungle_leaves",
        BlockId::AcaciaLog => "minecraft:acacia_log",
        BlockId::AcaciaLeaves => "minecraft:acacia_leaves",
        BlockId::MangroveLog => "minecraft:mangrove_log",
        BlockId::MangroveLeaves => "minecraft:mangrove_leaves",
        BlockId::CherryLog => "minecraft:cherry_log",
        BlockId::CherryLeaves => "minecraft:cherry_leaves",
        BlockId::SeaPickle => "minecraft:sea_pickle",
        BlockId::Seagrass => "minecraft:seagrass",
        BlockId::TallSeagrass => "minecraft:tall_seagrass",
        BlockId::Kelp => "minecraft:kelp",
        BlockId::KelpPlant => "minecraft:kelp_plant",
        BlockId::MossyCobblestone => "minecraft:mossy_cobblestone",
        BlockId::SandstoneSlab => "minecraft:sandstone_slab",
        BlockId::SuspiciousSand => "minecraft:suspicious_sand",
        BlockId::DripstoneBlock => "minecraft:dripstone_block",
        BlockId::PointedDripstone => "minecraft:pointed_dripstone",
        BlockId::SulfurSpike => "minecraft:sulfur_spike",
        BlockId::PotentSulfur => "minecraft:potent_sulfur",
        BlockId::BoneBlock => "minecraft:bone_block",
        BlockId::Chest => "minecraft:chest",
        BlockId::Spawner => "minecraft:spawner",
        BlockId::Bamboo => "minecraft:bamboo",
        BlockId::AmethystBlock => "minecraft:amethyst_block",
        BlockId::BuddingAmethyst => "minecraft:budding_amethyst",
        BlockId::SmoothBasalt => "minecraft:smooth_basalt",
        BlockId::SmallAmethystBud => "minecraft:small_amethyst_bud",
        BlockId::MediumAmethystBud => "minecraft:medium_amethyst_bud",
        BlockId::LargeAmethystBud => "minecraft:large_amethyst_bud",
        BlockId::AmethystCluster => "minecraft:amethyst_cluster",
        BlockId::SmallDripleaf => "minecraft:small_dripleaf",
        BlockId::BigDripleaf => "minecraft:big_dripleaf",
        BlockId::BigDripleafStem => "minecraft:big_dripleaf_stem",
        BlockId::CaveAir => "minecraft:cave_air",
        BlockId::TallGrass => "minecraft:tall_grass",
        BlockId::PaleMossCarpet | BlockId::PaleMossCarpetTopper => "minecraft:pale_moss_carpet",
        BlockId::RedMushroomBlock => "minecraft:red_mushroom_block",
        BlockId::BrownMushroomBlock => "minecraft:brown_mushroom_block",
        BlockId::MushroomStem => "minecraft:mushroom_stem",
    }
}

/// Vegetation classifier for BASE (no-veg) parity (moved from block_parity example).
pub fn is_vegetation_name(name: &str) -> bool {
    is_veg(name)
}

fn is_veg(name: &str) -> bool {
    let n = name.strip_prefix("minecraft:").unwrap_or(name);
    n.contains("leaves")
        || n.contains("log")
        || n.contains("wood")
        || n == "leaf_litter"
        || n == "vine"
        || n == "short_grass"
        || n == "tall_grass"
        || n == "grass"
        || n == "fern"
        || n == "large_fern"
        || n.contains("orchid")
        || n.contains("tulip")
        || n.contains("daisy")
        || n.contains("lilac")
        || n.contains("rose")
        || n.contains("peony")
        || n.contains("azalea")
        || n.contains("mushroom")
        || n == "dandelion"
        || n == "poppy"
        || n == "cornflower"
        || n == "oxeye_daisy"
        || n == "lily_of_the_valley"
        || n == "pink_petals"
        || n == "moss_carpet"
        || n == "moss_block"
        || n == "pale_moss_block"
        || n == "pale_moss_carpet"
        || n == "sculk"
        || n == "sculk_vein"
        || n == "sculk_sensor"
        || n == "sculk_catalyst"
        || n == "sculk_shrieker"
        || n == "glow_lichen"
        || n.contains("sapling")
        || n == "cave_vines"
        || n == "cave_vines_plant"
        || n == "hanging_roots"
        || n == "rooted_dirt"
        || n == "spore_blossom"
}
