// Copyright (c) 2026 Neutron Contributors -- MIT License
//
// Block IDs used internally by world generation.
//
// These are the internal IDs stored in `GeneratedChunk.blocks`. The parity
// tool maps them to vanilla resource locations for NBT serialization.

/// Minecraft block IDs used during chunk generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    Granite = 2,
    Diorite = 3,
    Andesite = 4,
    Dirt = 10,
    CoarseDirt = 11,
    GrassBlock = 12,
    Podzol = 14,
    Mycelium = 15,
    Cobblestone = 20,
    Sand = 24,
    RedSand = 25,
    Gravel = 26,
    GoldOre = 27,
    IronOre = 28,
    CoalOre = 29,
    CopperOre = 30,
    DeepslateIronOre = 31,
    RawIronBlock = 32,
    Bedrock = 33,
    RawCopperBlock = 34,
    DeepslateCoalOre = 35,
    DeepslateGoldOre = 36,
    DeepslateCopperOre = 37,
    DeepslateDiamondOre = 38,
    DeepslateRedstoneOre = 39,
    DeepslateLapisOre = 42,
    DiamondOre = 43,
    RedstoneOre = 44,
    LapisOre = 45,
    OakLog = 40,
    OakLeaves = 41,
    Water = 50,
    Lava = 51,
    Sandstone = 52,
    RedSandstone = 53,
    Ice = 54,
    Snow = 55,
    Clay = 56,
    PackedIce = 57,
    PowderSnow = 58,
    Terracotta = 59,
    WhiteTerracotta = 60,
    OrangeTerracotta = 61,
    BrownTerracotta = 62,
    BlackTerracotta = 63,
    Mud = 64,
    Deepslate = 65,
    Tuff = 66,
    Calcite = 67,
    BlueIce = 68,
    YellowTerracotta = 69,
    RedTerracotta = 70,
    LightGrayTerracotta = 71,
    /// Placeholder for 26.2 sulfur caves until palette is expanded.
    Cinnabar = 72,
    Sulfur = 73,
    Sculk = 74,
    SculkCatalyst = 75,
    SculkVein = 76,
    SculkSensor = 77,
    SculkShrieker = 78,
    MossBlock = 79,
    ShortGrass = 80,
    /// Surface leaf litter (1.21+).
    LeafLitter = 81,
    DarkOakLog = 82,
    DarkOakLeaves = 83,
    OakPlanks = 84,
    OakFence = 85,
}

impl BlockId {
    pub fn as_u16(self) -> u16 {
        self as u16
    }

    pub fn from_u16(v: u16) -> Option<Self> {
        match v {
            0 => Some(Self::Air),
            1 => Some(Self::Stone),
            2 => Some(Self::Granite),
            3 => Some(Self::Diorite),
            4 => Some(Self::Andesite),
            10 => Some(Self::Dirt),
            11 => Some(Self::CoarseDirt),
            12 => Some(Self::GrassBlock),
            14 => Some(Self::Podzol),
            15 => Some(Self::Mycelium),
            20 => Some(Self::Cobblestone),
            24 => Some(Self::Sand),
            25 => Some(Self::RedSand),
            26 => Some(Self::Gravel),
            27 => Some(Self::GoldOre),
            28 => Some(Self::IronOre),
            29 => Some(Self::CoalOre),
            30 => Some(Self::CopperOre),
            31 => Some(Self::DeepslateIronOre),
            32 => Some(Self::RawIronBlock),
            33 => Some(Self::Bedrock),
            34 => Some(Self::RawCopperBlock),
            35 => Some(Self::DeepslateCoalOre),
            36 => Some(Self::DeepslateGoldOre),
            37 => Some(Self::DeepslateCopperOre),
            38 => Some(Self::DeepslateDiamondOre),
            39 => Some(Self::DeepslateRedstoneOre),
            40 => Some(Self::OakLog),
            41 => Some(Self::OakLeaves),
            42 => Some(Self::DeepslateLapisOre),
            43 => Some(Self::DiamondOre),
            44 => Some(Self::RedstoneOre),
            45 => Some(Self::LapisOre),
            50 => Some(Self::Water),
            51 => Some(Self::Lava),
            52 => Some(Self::Sandstone),
            53 => Some(Self::RedSandstone),
            54 => Some(Self::Ice),
            55 => Some(Self::Snow),
            56 => Some(Self::Clay),
            57 => Some(Self::PackedIce),
            58 => Some(Self::PowderSnow),
            59 => Some(Self::Terracotta),
            60 => Some(Self::WhiteTerracotta),
            61 => Some(Self::OrangeTerracotta),
            62 => Some(Self::BrownTerracotta),
            63 => Some(Self::BlackTerracotta),
            64 => Some(Self::Mud),
            65 => Some(Self::Deepslate),
            66 => Some(Self::Tuff),
            67 => Some(Self::Calcite),
            68 => Some(Self::BlueIce),
            69 => Some(Self::YellowTerracotta),
            70 => Some(Self::RedTerracotta),
            71 => Some(Self::LightGrayTerracotta),
            72 => Some(Self::Cinnabar),
            73 => Some(Self::Sulfur),
            74 => Some(Self::Sculk),
            75 => Some(Self::SculkCatalyst),
            76 => Some(Self::SculkVein),
            77 => Some(Self::SculkSensor),
            78 => Some(Self::SculkShrieker),
            79 => Some(Self::MossBlock),
            80 => Some(Self::ShortGrass),
            81 => Some(Self::LeafLitter),
            82 => Some(Self::DarkOakLog),
            83 => Some(Self::DarkOakLeaves),
            84 => Some(Self::OakPlanks),
            85 => Some(Self::OakFence),
            _ => None,
        }
    }

    pub fn is_air(self) -> bool {
        self == Self::Air
    }

    pub fn is_fluid(self) -> bool {
        matches!(self, Self::Water | Self::Lava)
    }

    /// Parse a vanilla block name (`minecraft:grass_block`) to a BlockId.
    pub fn from_name(name: &str) -> Option<Self> {
        let n = name.strip_prefix("minecraft:").unwrap_or(name);
        match n {
            "air" | "cave_air" | "void_air" => Some(Self::Air),
            "stone" => Some(Self::Stone),
            "granite" => Some(Self::Granite),
            "diorite" => Some(Self::Diorite),
            "andesite" => Some(Self::Andesite),
            "dirt" => Some(Self::Dirt),
            "coarse_dirt" => Some(Self::CoarseDirt),
            "grass_block" => Some(Self::GrassBlock),
            "podzol" => Some(Self::Podzol),
            "mycelium" => Some(Self::Mycelium),
            "cobblestone" => Some(Self::Cobblestone),
            "sand" => Some(Self::Sand),
            "red_sand" => Some(Self::RedSand),
            "gravel" => Some(Self::Gravel),
            "gold_ore" => Some(Self::GoldOre),
            "iron_ore" => Some(Self::IronOre),
            "coal_ore" => Some(Self::CoalOre),
            "copper_ore" => Some(Self::CopperOre),
            "deepslate_iron_ore" => Some(Self::DeepslateIronOre),
            "deepslate_coal_ore" => Some(Self::DeepslateCoalOre),
            "deepslate_gold_ore" => Some(Self::DeepslateGoldOre),
            "deepslate_copper_ore" => Some(Self::DeepslateCopperOre),
            "deepslate_diamond_ore" => Some(Self::DeepslateDiamondOre),
            "deepslate_redstone_ore" => Some(Self::DeepslateRedstoneOre),
            "deepslate_lapis_ore" => Some(Self::DeepslateLapisOre),
            "diamond_ore" => Some(Self::DiamondOre),
            "redstone_ore" => Some(Self::RedstoneOre),
            "lapis_ore" => Some(Self::LapisOre),
            "raw_iron_block" => Some(Self::RawIronBlock),
            "raw_copper_block" => Some(Self::RawCopperBlock),
            "bedrock" => Some(Self::Bedrock),
            "water" => Some(Self::Water),
            "lava" => Some(Self::Lava),
            "sandstone" => Some(Self::Sandstone),
            "red_sandstone" => Some(Self::RedSandstone),
            "ice" => Some(Self::Ice),
            "snow_block" | "snow" => Some(Self::Snow),
            "clay" => Some(Self::Clay),
            "packed_ice" => Some(Self::PackedIce),
            "powder_snow" => Some(Self::PowderSnow),
            "terracotta" => Some(Self::Terracotta),
            "white_terracotta" => Some(Self::WhiteTerracotta),
            "orange_terracotta" => Some(Self::OrangeTerracotta),
            "brown_terracotta" => Some(Self::BrownTerracotta),
            "black_terracotta" => Some(Self::BlackTerracotta),
            "yellow_terracotta" => Some(Self::YellowTerracotta),
            "red_terracotta" => Some(Self::RedTerracotta),
            "light_gray_terracotta" => Some(Self::LightGrayTerracotta),
            "mud" => Some(Self::Mud),
            "deepslate" => Some(Self::Deepslate),
            "tuff" => Some(Self::Tuff),
            "calcite" => Some(Self::Calcite),
            "blue_ice" => Some(Self::BlueIce),
            "cinnabar" => Some(Self::Cinnabar),
            "sulfur" => Some(Self::Sulfur),
            "sculk" => Some(Self::Sculk),
            "sculk_catalyst" => Some(Self::SculkCatalyst),
            "sculk_vein" => Some(Self::SculkVein),
            "sculk_sensor" => Some(Self::SculkSensor),
            "sculk_shrieker" => Some(Self::SculkShrieker),
            "moss_block" => Some(Self::MossBlock),
            "short_grass" | "grass" | "tall_grass" => Some(Self::ShortGrass),
            "leaf_litter" => Some(Self::LeafLitter),
            "dark_oak_log" => Some(Self::DarkOakLog),
            "dark_oak_leaves" => Some(Self::DarkOakLeaves),
            "oak_log" => Some(Self::OakLog),
            "oak_leaves" => Some(Self::OakLeaves),
            "oak_planks" => Some(Self::OakPlanks),
            "oak_fence" => Some(Self::OakFence),
            _ => None,
        }
    }
}
